### ISSUE TITLE
KiMap indexer must assert correct namehash formation

### ISSUE THREAD

**Issue by mesozoic-technology** [kinode-dao/kinode#453]
A big component of our systems security comes down to correct application of the namehash algorithm.

The KiMap does not assert for correctly formed names beyond a very small subset of checks. For instance, a note entry must be prefixed with ~, and a name entry must not have that prefix.

But anything else is outside the bounds of the checks in the kimap.

Someone could technically register the following label "sub.nametheydonotown" underneath "kino", giving a name that could potentially look like "sub.nametheydonotown.kino". 

It would look like a subdomain of "nametheydonotown", but it's actually an invalid label.

We must assert correct namehashing for our indexers. Any label that is not a valid label must be discarded and not indexed.

**Comment by dr-frmr** [comment]
I added a function in process_lib that takes care of this consideration and applied it in kns_indexer:

https://github.com/kinode-dao/kinode/blob/d32673976829ee794091b2d5ba2f626513de5d00/kinode/packages/kns_indexer/kns_indexer/src/lib.rs#L302
